### ISSUE TITLE
Failed to transform locator 'MQGACF_ACTIVITY_TRACE.MQBACF_MESSAGE_DATA' value: 'null'

### ISSUE THREAD

**Issue by igorkry** [Nastel/tnt4j-streams#26]
017-02-28 12:09:16,376 DEBUG [10:WmqTraceStream:WmqActivityTraceStream!WmqTraceStream] - Trace message consumption check: PCF message is null | DEBUG | 2017-02-28 17:09:16.376000 UTC | RUNTIME=58004@IRGUN-PC#SERVER=IRGUN-PC#NETADDR=11.0.0.236#DATACENTER=UNKNOWN#GEOADDR=0,0
017-02-28 12:09:16,376 DEBUG [10:WmqTraceStream:WmqActivityTraceStream!WmqTraceStream] - Waiting for message on SYSTEM.ADMIN.TRACE.ACTIVITY.QUEUE | DEBUG | 2017-02-28 17:09:16.376000 UTC | RUNTIME=58004@IRGUN-PC#SERVER=IRGUN-PC#NETADDR=7:#DATACENTER=UNKNOWN#GEOADDR=0,0
017-02-28 12:09:16,378 DEBUG [10:WmqTraceStream:WmqActivityTraceStream!WmqTraceStream] - Read msg from SYSTEM.ADMIN.TRACE.ACTIVITY.QUEUE, total payload length=712 | DEBUG | 2017-02-28 17:09:16.378000 UTC | RUNTIME=58004@IRGUN-PC#SERVER=IRGUN-PC#NETADDR=7:#DATACENTER=UNKNOWN#GEOADDR=0,0
017-02-28 12:09:16,381 DEBUG [10:WmqTraceStream:WmqActivityTraceStream!WmqTraceStream] - Trace operation MQXF_CLOSE match stream defined operations set: true | DEBUG | 2017-02-28 17:09:16.381000 UTC | RUNTIME=58004@IRGUN-PC#SERVER=IRGUN-PC#NETADDR=7:#DATACENTER=UNKNOWN#GEOADDR=0,0
017-02-28 12:09:16,381 DEBUG [10:WmqTraceStream:WmqActivityTraceStream!WmqTraceStream] - Trace reason code MQRC_NONE is not in stream defined exclusions set: true | DEBUG | 2017-02-28 17:09:16.381000 UTC | RUNTIME=58004@7:N-PC#SERVER=7:N-PC#NETADDR=7:#DATACENTER=UNKNOWN#GEOADDR=0,0
017-02-28 12:09:16,382 DEBUG [10:WmqTraceStream:WmqActivityTraceStream!WmqTraceStream] - Trace message initiation: PCF message activity trace marker value: 1/1 | DEBUG | 2017-02-28 17:09:16.382000 UTC | RUNTIME=58004@7:N-PC#SERVER=7:N-PC#NETADDR=7:#DATACENTER=UNKNOWN#GEOADDR=0,0
017-02-28 12:09:16,382 DEBUG [10:WmqTraceStream:WmqActivityTraceStream!WmqTraceParser] - Parsing: com.ibm.mq.pcf.PCFMessage | DEBUG | 2017-02-28 17:09:16.382000 UTC | RUNTIME=58004@7:N-PC#SERVER=7:N-PC#NETADDR=7:#DATACENTER=UNKNOWN#GEOADDR=0,0
017-02-28 12:09:16,398 WARN  [10:WmqTraceStream:WmqActivityTraceStream!WmqTraceParser] - Failed to transform locator 'MQGACF_ACTIVITY_TRACE.MQBACF_MESSAGE_DATA' value: 'null' | WARNING | 2017-02-28 17:09:16.398000 UTC | RUNTIME=58004@7:N-PC#SERVER=7:N-PC#NETADDR=7:#DATACENTER=UNKNOWN#GE
ADDR=0,0
om.jkoolcloud.tnt4j.streams.transform.TransformationException: Failed to apply transformation 'fileName'
       at com.jkoolcloud.tnt4j.streams.transform.GroovyTransformation.transform(GroovyTransformation.java:57)
       at com.jkoolcloud.tnt4j.streams.fields.ActivityFieldLocator.transformValue(ActivityFieldLocator.java:489)
       at com.jkoolcloud.tnt4j.streams.parsers.GenericActivityParser.getLocatorValue(GenericActivityParser.java:408)
       at com.jkoolcloud.tnt4j.streams.parsers.GenericActivityParser.parseLocatorValues(GenericActivityParser.java:347)
       at com.jkoolcloud.tnt4j.streams.parsers.GenericActivityParser.parseLocatorValues(GenericActivityParser.java:326)
       at com.jkoolcloud.tnt4j.streams.parsers.GenericActivityParser.parsePreparedItem(GenericActivityParser.java:237)
       at com.jkoolcloud.tnt4j.streams.parsers.GenericActivityParser.parse(GenericActivityParser.java:207)
       at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.applyParsers(TNTParseableInputStream.java:167)
       at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.applyParsers(TNTParseableInputStream.java:142)
       at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.makeActivityInfo(TNTParseableInputStream.java:222)
       at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.processActivityItem(TNTParseableInputStream.java:244)
       at com.jkoolcloud.tnt4j.streams.inputs.TNTInputStream.run(TNTInputStream.java:690)
       at java.lang.Thread.run(Unknown Source)
aused by: java.lang.NullPointerException
       at java.lang.String.<init>(Unknown Source)
       at sun.reflect.GeneratedConstructorAccessor21.newInstance(Unknown Source)
       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
       at java.lang.reflect.Constructor.newInstance(Unknown Source)
       at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
       at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
       at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
       at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:255)
       at fileName.run(fileName:1)
       at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
       at groovy.lang.GroovyShell.evaluate(GroovyShell.java:623)
       at groovy.lang.GroovyShell.evaluate(GroovyShell.java:604)
       at com.jkoolcloud.tnt4j.streams.transform.GroovyTransformation.transform(GroovyTransformation.java:54)
       ... 12 more

**Comment by kausandr** [comment]
Prevent NPE in your transformatio script by adding this:
```groovy
$fieldValue == null ? null : new String ($fieldValue, "UTF-8")
```
