### ISSUE TITLE
activity trace streams crash

### ISSUE THREAD

**Issue by igorkry** [Nastel/tnt4j-streams#27]
this is the only trace i am able to share. it seems that it goes into loop 
in WmqTraceStream line code 174.
i can not reproduce it at will, but it seems to it relates to activity trace intercepts from the IIB 
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)
 at com.jkoolcloud.tnt4j.streams.custom.inputs.WmqTraceStream.getNextItem(WmqTraceStream.java:174)

**Comment by kausandr** [comment]
recursion changed to looping.
