### ISSUE TITLE
tnt4j streams terminates rather than recover after connection failure while sending

### ISSUE THREAD

**Issue by rnikula** [Nastel/tnt4j-streams#30]
2017-05-16 12:28:14,243 ERROR [9:WmqStream:WmqStream!TrackerImpl] - Failed to open event sink vm.name=55479@P1RAZ0080AS001, tid=9, event.sink=com.jkoolcloud.jesl.tnt4j.sink.JKCloudEventSink@a97d8ab(url: https://data.jkoolcloud.com:6585, jk.handle: com.jkoolcloud.jesl.net.JKClient@1a037526, piped.sink: com.jkoolcloud.tnt4j.sink.impl.FileEventSink@5177aec8), source=com.jkoolcloud.tnt4j.source.
java.io.IOException: Failed to connect to uri=https://data.jkoolcloud.com:6585, reason=Connection timed out (Connection timed out)
	at com.jkoolcloud.jesl.net.http.HttpClient.connect(HttpClient.java:171)
	at com.jkoolcloud.jesl.net.http.HttpClient.connect(HttpClient.java:180)
	at com.jkoolcloud.jesl.net.JKClient.connect(JKClient.java:128)
	at com.jkoolcloud.jesl.tnt4j.sink.JKCloudEventSink.open(JKCloudEventSink.java:250)
	at com.jkoolcloud.tnt4j.tracker.TrackerImpl.openEventSink(TrackerImpl.java:133)
	at com.jkoolcloud.tnt4j.tracker.TrackerImpl.open(TrackerImpl.java:683)
	at com.jkoolcloud.tnt4j.tracker.TrackerImpl.<init>(TrackerImpl.java:107)
	at com.jkoolcloud.tnt4j.tracker.DefaultTrackerFactory.getInstance(DefaultTrackerFactory.java:61)
	at com.jkoolcloud.tnt4j.TrackingLogger.getInstance(TrackingLogger.java:369)
	at com.jkoolcloud.tnt4j.streams.outputs.AbstractJKCloudOutput.getTracker(AbstractJKCloudOutput.java:216)
	at com.jkoolcloud.tnt4j.streams.outputs.JKCloudActivityOutput.logItem(JKCloudActivityOutput.java:72)
	at com.jkoolcloud.tnt4j.streams.outputs.JKCloudActivityOutput.logItem(JKCloudActivityOutput.java:37)
	at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.processActivityItem(TNTParseableInputStream.java:261)
	at com.jkoolcloud.tnt4j.streams.inputs.TNTInputStream.run(TNTInputStream.java:690)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:542)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:414)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
	at com.jkoolcloud.jesl.net.http.HttpClient.connect(HttpClient.java:167)
	... 14 more
2017-05-16 12:28:14,244 ERROR [9:WmqStream:WmqStream!WmqStream] - Failed to record activity at position 0: Tracker is not opened to record activity data... | ERROR | 2017-05-16 12:28:
java.lang.IllegalStateException: Tracker is not opened to record activity data...
	at com.jkoolcloud.tnt4j.streams.outputs.AbstractJKCloudOutput.checkTrackerState(AbstractJKCloudOutput.java:169)
	at com.jkoolcloud.tnt4j.streams.outputs.AbstractJKCloudOutput.getTracker(AbstractJKCloudOutput.java:217)
	at com.jkoolcloud.tnt4j.streams.outputs.JKCloudActivityOutput.logItem(JKCloudActivityOutput.java:72)
	at com.jkoolcloud.tnt4j.streams.outputs.JKCloudActivityOutput.logItem(JKCloudActivityOutput.java:37)
	at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.processActivityItem(TNTParseableInputStream.java:261)
	at com.jkoolcloud.tnt4j.streams.inputs.TNTInputStream.run(TNTInputStream.java:690)
	at java.lang.Thread.run(Thread.java:745)
2017-05-16 12:28:14,245 DEBUG [9:WmqStream:WmqStream!StreamsThread] - Signaled to stop 9:WmqStream:WmqStream

**Comment by amavashev** [comment]
Also important, why is there a TimeoutException. Possibly a socket leak or descriptor leak? The server side is available. Check for scoket leaks as well.

**Comment by kausandr** [comment]
Fixed in 40cdeb4e5a206080e25dfeea132b7a034deb5b6c
