### ISSUE TITLE
Caused by: java.lang.NullPointerException: Cannot invoke method replace() on null object

### ISSUE THREAD

**Issue by amavashev** [Nastel/tnt4j-streams#43]
<field name="ResourceName1" formattingPattern="{0}={1};Agent={2}">
            
            <field-locator locator="name(//*/*)" locator-type="Label">
                <field-map source="file" target="FILE"/>
                <field-map source="queue" target="QUEUE"/>
            </field-locator>
<field-locator locator="/${Direction}/file" locator-type="Label" required="false">
  <field-transform lang="groovy" name="DiffTransform">
                        $fieldValue.replace("@", "_")
        </field-transform>
 </field-locator>
 <field-locator locator="ts:getObjectName(/${Direction}/queue)" locator-type="Label" required="false"/>    
 
    <field-locator locator="/transaction/${Direction}Agent/@agent" locator-type="Label" required="false"/>
 </field>
i get error;
2018-06-19 10:25:25,401 WARN  [21:StreamBoundedExecutorThread-3!ActivityXmlParser] - Failed to transform locator '/${Direct
on}/file' value: 'null' | WARNING | 2018-06-19 14:25:25.401000 UTC | RUNTIME=21592@IRGUN-PC#SERVER=IRGUN-PC#NETADDR=11.0.0.
36#DATACENTER=UNKNOWN#GEOADDR=0,0
com.jkoolcloud.tnt4j.streams.transform.TransformationException: Failed to apply transformation 'DiffTransform'
        at com.jkoolcloud.tnt4j.streams.transform.GroovyTransformation.transform(GroovyTransformation.java:70)
        at com.jkoolcloud.tnt4j.streams.fields.AbstractFieldEntity.transformValue(AbstractFieldEntity.java:140)
        at com.jkoolcloud.tnt4j.streams.parsers.GenericActivityParser.getLocatorValue(GenericActivityParser.java:742)
        at com.jkoolcloud.tnt4j.streams.parsers.GenericActivityParser.parseLocatorValues(GenericActivityParser.java:657)
        at com.jkoolcloud.tnt4j.streams.parsers.ActivityXmlParser.parsePreparedItem(ActivityXmlParser.java:299)
        at com.jkoolcloud.tnt4j.streams.parsers.GenericActivityParser.parse(GenericActivityParser.java:360)
        at com.jkoolcloud.tnt4j.streams.parsers.ActivityParser.applyStackedParser(ActivityParser.java:168)
        at com.jkoolcloud.tnt4j.streams.parsers.ActivityParser.applyFieldValue(ActivityParser.java:156)
        at com.jkoolcloud.tnt4j.streams.parsers.GenericActivityParser.applyDynamicValue(GenericActivityParser.java:587)
        at com.jkoolcloud.tnt4j.streams.parsers.GenericActivityParser.applyFieldValue(GenericActivityParser.java:520)
        at com.jkoolcloud.tnt4j.streams.parsers.ActivityXmlParser.parsePreparedItem(ActivityXmlParser.java:316)
        at com.jkoolcloud.tnt4j.streams.parsers.GenericActivityParser.parse(GenericActivityParser.java:360)
        at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.applyParsers(TNTParseableInputStream.java:208)
        at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.applyParsers(TNTParseableInputStream.java:183)
        at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.makeActivityInfo(TNTParseableInputStream.java:276)
        at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.processActivityItem(TNTParseableInputStream.java:298

        at com.jkoolcloud.tnt4j.streams.inputs.TNTInputStream$ActivityItemProcessingTask.run(TNTInputStream.java:1057)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke method replace() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at DiffTransform.run(DiffTransform:1)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:585)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:623)
        at groovy.lang.GroovyShell.evaluate(GroovyShell.java:604)
        at com.jkoolcloud.tnt4j.streams.transform.GroovyTransformation.transform(GroovyTransformation.java:67)
        ... 21 more

**Comment by kausandr** [comment]
Add null check, or use StringUtils.replace($fieldValue, "@", "_")
