### ISSUE TITLE
Support custom property fields in tnt4j stream

### ISSUE THREAD

**Issue by igorkry** [Nastel/tnt4j-streams#5]
how to handle properties in tnt4j?
2016-12-01 09:05:19,179 ERROR [main!StreamsAgent] - Parser MQFTEParserNormal already has field named Custom, at line 109 |
org.xml.sax.SAXException: Parser 'MQFTEParserNormal' already has field named 'Custom', at line 109
java.lang.IllegalArgumentException: Parser 'MQFTEParserNormal' already has field named 'Custom'
        at com.jkoolcloud.tnt4j.streams.configure.sax.ConfigParserHandler.endElement(ConfigParserHandler.java:1149)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
        at com.jkoolcloud.tnt4j.streams.configure.sax.StreamsConfigSAXParser.parse(StreamsConfigSAXParser.java:80)
        at com.jkoolcloud.tnt4j.streams.configure.StreamsConfigLoader.load(StreamsConfigLoader.java:153)
        at com.jkoolcloud.tnt4j.streams.configure.StreamsConfigLoader.<init>(StreamsConfigLoader.java:103)
        at com.jkoolcloud.tnt4j.streams.StreamsAgent.loadConfigAndRun(StreamsAgent.java:181)
        at com.jkoolcloud.tnt4j.streams.StreamsAgent.loadConfigAndRun(StreamsAgent.java:175)
        at com.jkoolcloud.tnt4j.streams.StreamsAgent.main(StreamsAgent.java:88)
Caused by: java.lang.IllegalArgumentException: Parser 'MQFTEParserNormal' already has field named 'Custom'
        at com.jkoolcloud.tnt4j.streams.parsers.GenericActivityParser.addField(GenericActivityParser.java:105)
        at com.jkoolcloud.tnt4j.streams.configure.sax.ConfigParserHandler.endElement(ConfigParserHandler.java:1112)
        ... 18 more

**Comment by kausandr** [comment]
Set field name not from predefined names set and such field will go as activity/event/snapshot property. See streams Readme.md for details.
