### ISSUE TITLE
Support DF similar field-map functions in tnt4j

### ISSUE THREAD

**Issue by igorkry** [Nastel/tnt4j-streams#7]
example:
<field name="StatusCode" locator="/transaction/status/@resultCode" locator-type="Label" datatype="Number">
			<field-map source="0" target="SUCCESS"/>
			<field-map source="40" target="WARNING"/>
			<field-map source="" target="ERROR"/>
errors:
2016-12-01 09:47:10,835 ERROR [10:WmqStream:WmqStream!WmqStream] - Failed to record activity at position 0: Failed to process activity data at position 0
java.text.ParseException: Failed to process activity data at position 0
        at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.makeActivityInfo(TNTParseableInputStream.java:225)
        at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.processActivityItem(TNTParseableInputStream.java:244)
        at com.jkoolcloud.tnt4j.streams.inputs.TNTInputStream.run(TNTInputStream.java:629)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.text.ParseException: Failed parsing data for field StatusCode
        at com.jkoolcloud.tnt4j.streams.parsers.ActivityXmlParser.parsePreparedItem(ActivityXmlParser.java:278)
        at com.jkoolcloud.tnt4j.streams.parsers.ActivityXmlParser.parse(ActivityXmlParser.java:215)
        at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.applyParsers(TNTParseableInputStream.java:167)
        at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.applyParsers(TNTParseableInputStream.java:142)
        at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.makeActivityInfo(TNTParseableInputStream.java:222)
        ... 3 more
Caused by: java.lang.NumberFormatException: ERROR is not a valid number.
        at org.apache.commons.lang3.math.NumberUtils.createNumber(NumberUtils.java:574)
        at com.jkoolcloud.tnt4j.streams.fields.ActivityInfo.getNumberValue(ActivityInfo.java:985)
        at com.jkoolcloud.tnt4j.streams.fields.ActivityInfo.getPropertyValue(ActivityInfo.java:380)
        at com.jkoolcloud.tnt4j.streams.fields.ActivityInfo.setFieldValue(ActivityInfo.java:356)
        at com.jkoolcloud.tnt4j.streams.fields.ActivityInfo.applyField(ActivityInfo.java:153)
        at com.jkoolcloud.tnt4j.streams.parsers.ActivityParser.applyFieldValue(ActivityParser.java:126)
        at com.jkoolcloud.tnt4j.streams.parsers.MessageActivityXmlParser.applyFieldValue(MessageActivityXmlParser.java:192)
        at com.jkoolcloud.tnt4j.streams.parsers.ActivityParser.applyFieldValue(ActivityParser.java:152)
        at com.jkoolcloud.tnt4j.streams.parsers.ActivityXmlParser.parsePreparedItem(ActivityXmlParser.java:268)
        ... 7 more

**Comment by kausandr** [comment]
There is field-map. See readme.md and samples.
