### ISSUE TITLE
java.lang.NullPointerException: opType must be non-null

### ISSUE THREAD

**Issue by igorkry** [Nastel/tnt4j-streams#8]
Assumption that opType is a required field in tnt4j streams. The parser config has no reference of such a field. In DF this field is ActivityType is the field we use to map operation type.  
what should it be for operation type filed?

2016-12-01 12:37:10,751 DEBUG [10:WmqStream:WmqStream!MessageActivityXmlParser] - Parsing: <?xml version="1.0" encoding="UTF-8"?><transaction version="6.00" ID="414d512041474e543120202020202020d9433358207efb23" agentRole="sourceAgent" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="TransferLog.xsd" xmlns=""><action time="2016-12-01T17:37:53.747Z">started</action><sourceAgent agent="AGNT1A" QMgr="AGNT1" agentType="STANDARD"><systemInfo architecture="x86" name="Windows 7" version="6.1 build 7601 Service Pack 1"/></sourceAgent><destinationAgent agent="AGNT1A" QMgr="AGNT1"></destinationAgent><originator><hostName>192.168.188.1</hostName><userID>user</userID><mqmdUserID>user</mqmdUserID></originator><transferSet startTime="2016-12-01T17:37:53.747Z" total="1" bytesSent="0"><metaDataSet><metaData key="com.ibm.wmqfte.SourceAgent">AGNT1A</metaData><metaData key="com.ibm.wmqfte.DestinationAgent">AGNT1A</metaData><metaData key="com.ibm.wmqfte.MqmdUser">user</metaData><metaData key="com.ibm.wmqfte.OriginatingUser">user</metaData><metaData key="com.ibm.wmqfte.OriginatingHost">192.168.188.1</metaData><metaData key="com.ibm.wmqfte.TransferId">414d512041474e543120202020202020d9433358207efb23</metaData><metaData key="com.ibm.wmqfte.JobName">Monitor for SUNGUARD files</metaData><metaData key="com.ibm.wmqfte.Priority">4</metaData></metaDataSet></transferSet><job><name>Monitor for SUNGUARD files</name></job></transaction> | DEBUG | 2016-12-01 17:37:10.751000 UTC | RUNTIME=84780@IRGUN-PC#SERVER=IRGUN-PC#NETADDR=11.0.0.236#DATACENTER=UNKNOWN#GEOADDR=0,0
2016-12-01 12:37:10,798 DEBUG [10:WmqStream:WmqStream!JKCloudActivityOutput] - Build new tracker for source APPL=JOB:Monitor for SUNGUARD files#SERVER=192.168.188.1#NETADDR=  | DEBUG | 2016-12-01 17:37:10.798000 UTC | RUNTIME=84780@IRGUN-PC#SERVER=IRGUN-PC#NETADDR=11.0.0.236#DATACENTER=UNKNOWN#GEOADDR=0,0
2016-12-01 12:37:10,802 ERROR [10:WmqStream:WmqStream!WmqStream] - Failed to record activity at position 0: opType must be non-null | ERROR | 2016-12-01 17:37:10.801000 UTC | RUNTIME=84780@IRGUN-PC#SERVER=IRGUN-PC#NETADDR=11.0.0.236#DATACENTER=UNKNOWN#GEOADDR=0,0
java.lang.NullPointerException: opType must be non-null
	at com.jkoolcloud.tnt4j.core.Operation.setType(Operation.java:232)
	at com.jkoolcloud.tnt4j.streams.fields.ActivityInfo.buildEvent(ActivityInfo.java:690)
	at com.jkoolcloud.tnt4j.streams.fields.ActivityInfo.buildTrackable(ActivityInfo.java:603)
	at com.jkoolcloud.tnt4j.streams.fields.ActivityInfo.recordActivity(ActivityInfo.java:591)
	at com.jkoolcloud.tnt4j.streams.outputs.JKCloudActivityOutput.logItem(JKCloudActivityOutput.java:59)
	at com.jkoolcloud.tnt4j.streams.outputs.JKCloudActivityOutput.logItem(JKCloudActivityOutput.java:32)
	at com.jkoolcloud.tnt4j.streams.inputs.TNTParseableInputStream.processActivityItem(TNTParseableInputStream.java:261)
	at com.jkoolcloud.tnt4j.streams.inputs.TNTInputStream.run(TNTInputStream.java:629)
	at java.lang.Thread.run(Unknown Source)

**Comment by kausandr** [comment]
It is 'EventType'
